app = 'service-api'
primary_region = 'syd'

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    handlers = ["http"]
    port = 3000
    force_https = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
