# node-graphql/docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=campaign
      - PGPORT=5433
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'
volumes:
  postgres:
