# fly.toml app configuration file generated for service-user on 2024-04-27T13:03:21+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'service-user'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
