name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      # - run: yarn nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v4
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}

      - run: yarn nx-cloud record -- nx format:check
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - run: yarn nx affected -t lint test build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: yarn deploy:service-api
        if: ${{ github.ref_name == 'main' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
